export const data = {
  fiatCurrencies: {
    usd: { name: "US Dollar", symbol: "$" },
    eur: { name: "Euro", symbol: "€" },
    gbp: { name: "British Pound", symbol: "£" },
    jpy: { name: "Japanese Yen", symbol: "¥" },
    krw: { name: "South Korean Won", symbol: "₩" },
    aud: { name: "Australian Dollar", symbol: "$" },
    cad: { name: "Canadian Dollar", symbol: "$" },
    chf: { name: "Swiss Franc", symbol: "CHF" },
    cny: { name: "Chinese Yuan Renminbi", symbol: "¥" },
    inr: { name: "Indian Rupee", symbol: "₹" },
    rub: { name: "Russian Ruble", symbol: "₽" },
    aed: { name: "Emirati Dirham", symbol: "د.إ" },
    nzd: { name: "New Zealand Dollar", symbol: "$" },
    zard: { name: "South African Rand", symbol: "R" },
    mxn: { name: "Mexican Peso", symbol: "$" },
    try: { name: "Turkish Lira", symbol: "₺" },
    hkd: { name: "Hong Kong Dollar", symbol: "$" },
    dkk: { name: "Danish Krone", symbol: "kr" },
    nok: { name: "Norwegian Krone", symbol: "kr" },
    sek: { name: "Swedish Krona", symbol: "kr" },
    huf: { name: "Hungarian Forint", symbol: "Ft" },
    pln: { name: "Polish Zloty", symbol: "zł" },
    myr: { name: "Malaysian Ringgit", symbol: "RM" },
    php: { name: "Philippine Peso", symbol: "₱" },
    bbd: { name: "Barbadian Dollar", symbol: "$" },
    ars: { name: "Argentine Peso", symbol: "$" },
    bob: { name: "Bolivian Bolíviano", symbol: "Bs" },
    brl: { name: "Brazilian Real", symbol: "R$" },
    cop: { name: "Colombian Peso", symbol: "$" },
    egp: { name: "Egyptian Pound", symbol: "ج.م" },
    dzd: { name: "Algerian Dinar", symbol: "د.ج" },
    skr: { name: "Sri Lankan Rupee", symbol: "Rs" },
    afn: { name: "Afghan Afghani", symbol: "؋" },
    all: { name: "Albanian Lek", symbol: "L" },
    amd: { name: "Armenian Dram", symbol: "֏" },
    gjn: { name: "Ghanaian Cedi", symbol: "₵" },
    iqd: { name: "Iraqi Dinar", symbol: "ع.د" },
    syp: { name: "Syrian Pound", symbol: "ل.س" },
    uah: { name: "Ukrainian Hryvnia", symbol: "₴" },
    lkr: { name: "Sri Lankan Rupee", symbol: "Rs" },
  },
  cryptocurrencies: {
    "1inch": { name: "1inch", symbol: "1INCH" },
    aave: { name: "Aave", symbol: "AAVE" },
    ada: { name: "Cardano", symbol: "ADA" },
    agix: { name: "SingularityNET", symbol: "AGIX" },
    amp: { name: "Amp", symbol: "AMP" },
    ape: { name: "ApeCoin", symbol: "APE" },
    apt: { name: "Aptos", symbol: "APT" },
    ar: { name: "Arweave", symbol: "AR" },
    arb: { name: "Arbitrum", symbol: "ARB" },
    atom: { name: "Cosmos", symbol: "ATOM" },
    avax: { name: "Avalanche", symbol: "AVAX" },
    bch: { name: "Bitcoin Cash", symbol: "BCH" },
    bnb: { name: "Binance Coin", symbol: "BNB" },
    bsv: { name: "Bitcoin SV", symbol: "BSV" },
    btc: { name: "Bitcoin", symbol: "BTC" },
    busd: { name: "Binance USD", symbol: "BUSD" },
    cake: { name: "PancakeSwap", symbol: "CAKE" },
    celo: { name: "Celo", symbol: "CELO" },
    chz: { name: "Chiliz", symbol: "CHZ" },
    comp: { name: "Compound", symbol: "COMP" },
    cro: { name: "Crypto.com Chain", symbol: "CRO" },
    crv: { name: "Curve DAO Token", symbol: "CRV" },
    dai: { name: "DAI", symbol: "DAI" },
    dash: { name: "Digital Cash", symbol: "DASH" },
    dcr: { name: "Decred", symbol: "DCR" },
    doge: { name: "Dogecoin", symbol: "DOGE" },
    dot: { name: "Polkadot", symbol: "DOT" },
    egld: { name: "Elrond", symbol: "EGLD" },
    enj: { name: "Enjin Coin", symbol: "ENJ" },
    eos: { name: "EOS", symbol: "EOS" },
    eth: { name: "Ethereum", symbol: "ETH" },
    frax: { name: "Frax", symbol: "FRAX" },
    ftm: { name: "Fantom", symbol: "FTM" },
    gala: { name: "Gala", symbol: "GALA" },
    link: { name: "Chainlink", symbol: "LINK" },
    ltc: { name: "Litecoin", symbol: "LTC" },
    mana: { name: "Mana Coin Decentraland", symbol: "MANA" },
    matic: { name: "Polygon", symbol: "MATIC" },
    mkd: { name: "Maker", symbol: "MKR" },
    near: { name: "NEAR Protocol", symbol: "NEAR" },
    neo: { name: "NEO", symbol: "NEO" },
    okb: { name: "Okex", symbol: "OKB" },
    paxg: { name: "PAX Gold", symbol: "PAXG" },
    shib: { name: "Shiba Inu", symbol: "SHIB" },
    snx: { name: "Synthetix Network", symbol: "SNX" },
    sol: { name: "Solana", symbol: "SOL" },
    trx: { name: "TRON", symbol: "TRX" },
    usdt: { name: "Tether", symbol: "USDT" },
    vet: { name: "Vechain", symbol: "VET" },
    waves: { name: "Waves", symbol: "WAVES" },
    xrp: { name: "Ripple", symbol: "XRP" },
    zec: { name: "ZCash", symbol: "ZEC" },
  },
};
