export const data = {
  fiatCurrencies: {
    usd: { name: "US Dollar", symbol: "$" },
    eur: { name: "Euro", symbol: "€" },
    gbp: { name: "British Pound", symbol: "£" },
    jpy: { name: "Japanese Yen", symbol: "¥" },
    krw: { name: "South Korean Won", symbol: "₩" },
    aud: { name: "Australian Dollar", symbol: "$" },
    cad: { name: "Canadian Dollar", symbol: "$" },
    chf: { name: "Swiss Franc", symbol: "CHF" },
    cny: { name: "Chinese Yuan Renminbi", symbol: "¥" },
    inr: { name: "Indian Rupee", symbol: "₹" },
    rub: { name: "Russian Ruble", symbol: "₽" },
    aed: { name: "Emirati Dirham", symbol: "د.إ" },
    nzd: { name: "New Zealand Dollar", symbol: "$" },
    zard: { name: "South African Rand", symbol: "R" },
    mxn: { name: "Mexican Peso", symbol: "$" },
    try: { name: "Turkish Lira", symbol: "₺" },
    hkd: { name: "Hong Kong Dollar", symbol: "$" },
    dkk: { name: "Danish Krone", symbol: "kr" },
    nok: { name: "Norwegian Krone", symbol: "kr" },
    sek: { name: "Swedish Krona", symbol: "kr" },
    huf: { name: "Hungarian Forint", symbol: "Ft" },
    pln: { name: "Polish Zloty", symbol: "zł" },
    myr: { name: "Malaysian Ringgit", symbol: "RM" },
    php: { name: "Philippine Peso", symbol: "₱" },
    bbd: { name: "Barbadian Dollar", symbol: "$" },
    ars: { name: "Argentine Peso", symbol: "$" },
    bob: { name: "Bolivian Bolíviano", symbol: "Bs" },
    brl: { name: "Brazilian Real", symbol: "R$" },
    cop: { name: "Colombian Peso", symbol: "$" },
    egp: { name: "Egyptian Pound", symbol: "ج.م" },
    dzd: { name: "Algerian Dinar", symbol: "د.ج" },
    skr: { name: "Sri Lankan Rupee", symbol: "Rs" },
    afn: { name: "Afghan Afghani", symbol: "؋" },
    all: { name: "Albanian Lek", symbol: "L" },
    amd: { name: "Armenian Dram", symbol: "֏" },
    gjn: { name: "Ghanaian Cedi", symbol: "₵" },
    iqd: { name: "Iraqi Dinar", symbol: "ع.د" },
    syp: { name: "Syrian Pound", symbol: "ل.س" },
    uah: { name: "Ukrainian Hryvnia", symbol: "₴" },
    lkr: { name: "Sri Lankan Rupee", symbol: "Rs" },
  },
  cryptocurrencies: {
    "1inch": "1inch",
    aave: "Aave",
    ada: "Cardano",
    agix: "SingularityNET",
    amp: "Amp",
    ape: "ApeCoin",
    apt: "Aptos",
    ar: "Arweave",
    arb: "Arbitrum",
    atom: "Cosmos",
    avax: "Avalanche",
    bch: "Bitcoin Cash",
    bnb: "Binance Coin",
    bsv: "Bitcoin SV",
    btc: "Bitcoin",
    busd: "Binance USD",
    cake: "PancakeSwap",
    celo: "Celo",
    chz: "Chiliz",
    comp: "Compound",
    cro: "Crypto.com Chain",
    crv: "Curve DAO Token",
    dai: "DAI",
    dash: "Digital Cash",
    dcr: "Decred",
    doge: "Dogecoin",
    dot: "Polkadot",
    egld: "Elrond",
    enj: "Enjin Coin",
    eos: "EOS",
    eth: "Ethereum",
    frax: "Frax",
    ftm: "Fantom",
    gala: "Gala",
    link: "Chainlink",
    ltc: "Litecoin",
    mana: "Mana Coin Decentraland",
    matic: "Polygon",
    mkd: "Maker",
    near: "NEAR Protocol",
    neo: "NEO",
    okb: "Okex",
    paxg: "PAX Gold",
    shib: "Shiba Inu",
    snx: "Synthetix Network",
    sol: "Solana",
    trx: "TRON",
    usdt: "Tether",
    vet: "Vechain",
    waves: "Waves",
    xrp: "Ripple",
    zec: "ZCash",
  },
};
