export const data = {
  fiatCurrencies: {
    aed: { name: "Emirati Dirham", symbol: "د.إ" },
    afn: { name: "Afghan Afghani", symbol: "؋" },
    all: { name: "Albanian Lek", symbol: "L" },
    amd: { name: "Armenian Dram", symbol: "֏" },
    ars: { name: "Argentine Peso", symbol: "$" },
    aud: { name: "Australian Dollar", symbol: "$" },
    bam: { name: "Bosnian Convertible Mark", symbol: "KM" },
    bbd: { name: "Barbadian Dollar", symbol: "$" },
    bgn: { name: "Bulgarian Lev", symbol: "лв" },
    bhd: { name: "Bahraini Dinar", symbol: ".د.ب" },
    bmd: { name: "Bermudian Dollar", symbol: "$" },
    bob: { name: "Bolivian Bolíviano", symbol: "Bs" },
    brl: { name: "Brazilian Real", symbol: "R$" },
    cad: { name: "Canadian Dollar", symbol: "$" },
    chf: { name: "Swiss Franc", symbol: "CHF" },
    cny: { name: "Chinese Yuan Renminbi", symbol: "¥" },
    cop: { name: "Colombian Peso", symbol: "$" },
    crc: { name: "Costa Rican Colon", symbol: "₡" },
    czk: { name: "Czech Koruna", symbol: "Kč" },
    djf: { name: "Djiboutian Franc", symbol: "Fdj" },
    dkk: { name: "Danish Krone", symbol: "kr" },
    dop: { name: "Dominican Peso", symbol: "$" },
    dzd: { name: "Algerian Dinar", symbol: "د.ج" },
    egp: { name: "Egyptian Pound", symbol: "ج.م" },
    eur: { name: "Euro", symbol: "€" },
    gbp: { name: "British Pound", symbol: "£" },
    gel: { name: "Georgian Lari", symbol: "₾" },
    hkd: { name: "Hong Kong Dollar", symbol: "$" },
    huf: { name: "Hungarian Forint", symbol: "Ft" },
    inr: { name: "Indian Rupee", symbol: "₹" },
    jpy: { name: "Japanese Yen", symbol: "¥" },
    krw: { name: "South Korean Won", symbol: "₩" },
    mxn: { name: "Mexican Peso", symbol: "$" },
    nzd: { name: "New Zealand Dollar", symbol: "$" },
    pen: { name: "Peruvian Sol", symbol: "S/" },
    rub: { name: "Russian Ruble", symbol: "₽" },
    sar: { name: "Saudi Arabian Riyal", symbol: "ر.س" },
    sek: { name: "Swedish Krona", symbol: "kr" },
    sgd: { name: "Singapore Dollar", symbol: "$" },
    try: { name: "Turkish Lira", symbol: "₺" },
    usd: { name: "US Dollar", symbol: "$" },
    vnd: { name: "Vietnamese Dong", symbol: "₫" },
  },
  cryptocurrencies: {
    "1inch": "1inch",
    aave: "Aave",
    ada: "Cardano",
    agix: "SingularityNET",
    amp: "Amp",
    ape: "ApeCoin",
    apt: "Aptos",
    ar: "Arweave",
    arb: "Arbitrum",
    atom: "Cosmos",
    avax: "Avalanche",
    bch: "Bitcoin Cash",
    bnb: "Binance Coin",
    bsv: "Bitcoin SV",
    btc: "Bitcoin",
    busd: "Binance USD",
    cake: "PancakeSwap",
    celo: "Celo",
    chz: "Chiliz",
    comp: "Compound",
    cro: "Crypto.com Chain",
    crv: "Curve DAO Token",
    dai: "DAI",
    dash: "Digital Cash",
    dcr: "Decred",
    doge: "Dogecoin",
    dot: "Polkadot",
    egld: "Elrond",
    enj: "Enjin Coin",
    eos: "EOS",
    eth: "Ethereum",
    frax: "Frax",
    ftm: "Fantom",
    gala: "Gala",
    link: "Chainlink",
    ltc: "Litecoin",
    mana: "Mana Coin Decentraland",
    matic: "Polygon",
    mkd: "Maker",
    near: "NEAR Protocol",
    neo: "NEO",
    okb: "Okex",
    paxg: "PAX Gold",
    shib: "Shiba Inu",
    snx: "Synthetix Network",
    sol: "Solana",
    trx: "TRON",
    usdt: "Tether",
    vet: "Vechain",
    waves: "Waves",
    xrp: "Ripple",
    zec: "ZCash",
  },
};
